language: node_js
node_js:
  - "node"

before_script:
  - npm install -g firebase-tools

script:
  - npm test
  - npm run build

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}

notifications:
  email: false
